name: wash_up
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  lottie: ^3.3.3
  dots_indicator: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  # example:
  fonts:
   - family: Cairo
     fonts:
      - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
   - family: Inter
     fonts:
      - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
   - family: Almarai
     fonts:
       - asset: assets/fonts/Almarai/Almarai-Regular.ttf
