// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJ7n_vxlcdYo_TvJrVmUmBGhOjY5-P4w',
    appId: '1:773152430496:web:5d0bea962aa87583f4acc5',
    messagingSenderId: '773152430496',
    projectId: 'car-wash-1ca9b',
    authDomain: 'car-wash-1ca9b.firebaseapp.com',
    storageBucket: 'car-wash-1ca9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZsyBd7lkh-VHxBOccE1k0L6UWH488zE',
    appId: '1:773152430496:android:566db5546a7f421ef4acc5',
    messagingSenderId: '773152430496',
    projectId: 'car-wash-1ca9b',
    storageBucket: 'car-wash-1ca9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuV8faAnxXk_6_H5QcLGmrIqZLCSf3WQQ',
    appId: '1:773152430496:ios:10381cdb8d800b66f4acc5',
    messagingSenderId: '773152430496',
    projectId: 'car-wash-1ca9b',
    storageBucket: 'car-wash-1ca9b.firebasestorage.app',
    iosBundleId: 'com.example.washUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuV8faAnxXk_6_H5QcLGmrIqZLCSf3WQQ',
    appId: '1:773152430496:ios:10381cdb8d800b66f4acc5',
    messagingSenderId: '773152430496',
    projectId: 'car-wash-1ca9b',
    storageBucket: 'car-wash-1ca9b.firebasestorage.app',
    iosBundleId: 'com.example.washUp',
  );
}
